### ISSUE TITLE
Converted pages are not deleted

### ISSUE THREAD

**Issue by ts72372** [chris-kent/Confluence-Blog-Tools#37] opened 2018-11-28 13:04 UTC
When a page is converted to a blog post, the confluence page persists and will not be deleted. The site is thus available as a Confluence page and as a blog post.

When a page is converted to a blog post, the confluence page should be deleted.

**Comment by chris-kent** [comment] 2018-12-03 10:43
Hi,
From the information you have provided I am unable to diagnose this issue, can you please provide more information.

**Tips for Raising Problem Tickets**
Specify Atlassian product version and plugin version
Provide detailed steps to reproduce the problem
Enable logging for the plugin (add class net.kentcom with ALL) in the Logging and Profile admin setup, repeat the failure to capture information in the Confluence log.
Attach the resulting log entries from the Confluence log file which capture logging at the time of the failure.

**Comment by chris-kent** [comment] 2019-01-16 09:55
If this is no longer an issue, I will close this ticket

**Comment by ts72372** [comment] 2019-01-16 09:57
First: Convert Confluence Page to Blog
Second: Blog exists
Third: Confluence Page also exists
Fourth: The converted Confluence page is not removed automatically.

**Comment by ts72372** [comment] 2019-01-16 09:58
Four is the problem. The page should be removed automatically.

**Comment by chris-kent** [comment] 2019-01-16 12:07
Hi,

Can you please provide the following information, the details provided do not allow me to rectify the issue. In particular steps 3 and 4 are critical to show me the errors.

Tips for Raising Problem Tickets
1. Specify Atlassian product version and plugin version
2. Provide detailed steps to reproduce the problem
3. Enable logging for the plugin (add class net.kentcom with ALL) in the Logging and Profile admin setup, Repeat the failure to capture information in the Confluence log.
4. Attach the resulting log entries from the Confluence log file which capture logging at the time of the failure.

**Comment by chris-kent** [comment] 2019-04-02 03:28
Closed due to inactivity

**Closed by chris-kent** 2019-04-02 03:28 UTC
